### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ZehelFenris** [AvyAddons/BetterBags_Dragonflight#1]
### Description

[Greater Encapsulated Destiny](https://www.wowhead.com/item=207027/greater-encapsulated-destiny) is not sorted into Time Rift it seems to use it's default sorting

### Addon Version

v1.0.1

### World of Warcraft Flavor

Retail (Dragonflight)

### Tested with only BetterBags_Dragonflight

- [ ] Yes
- [X] No

### Reproduction Steps

Open bags and it's under Consumable for me.

**Comment by lucasvienna** [comment]
Added in [v1.0.2](https://github.com/AvyAddons/BetterBags_Dragonflight/releases/tag/v1.0.2), thanks for the report!
