### ISSUE TITLE
[BUG] Attempted to add item 199343 to category Treasure Sacks, but the item does not exist.

### ISSUE THREAD

**Issue by GrumpyWolf92** [AvyAddons/BetterBags_Dragonflight#2]
### Description

Attempted to add item 199343 to category Treasure Sacks, but the item does not exist. This error occurs on each log in and I've narrowed it down to this plugin. Not sure if it's something on my end or what :)

### Addon Version

v1.0.3

### World of Warcraft Flavor

Retail (Dragonflight)

### Tested with only BetterBags_Dragonflight

- [X] Yes
- [ ] No

### Lua Error

14x BetterBags/data/categories.lua:54: Attempted to add item 199343 to category Treasure Sacks, but the item does not exist.
[string "=[C]"]: in function `assert'
[string "@BetterBags/data/categories.lua"]:54: in function `AddItemToCategory'
[string "@BetterBags_Dragonflight/main.lua"]:12: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "Attempted to add item 199343 to category Treasure Sacks, but the item does not exist."

### Reproduction Steps

1. Enable BetterBags and BetterBags Dragonflight
2. Log in or reload

**Comment by lucasvienna** [comment]
Thanks for the report! I've noticed a similar message, but the item ID was `202104`. It seems some items were removed in the recent patch and are no longer in the game. I'll do a proper pass and hopefully deal with all such cases.

**Comment by lucasvienna** [comment]
Fixed in [v1.0.4](https://github.com/AvyAddons/BetterBags_Dragonflight/releases/tag/v1.0.4)
