### ISSUE TITLE
Save location of window anchor 

### ISSUE THREAD

**Issue by Milky063** [AvyAddons/BetterBags_Dragonflight#3]
## Feature Request
Is there a way to save the location of each window for each toon.

### Is your feature request related to a problem?
_A clear and concise description of what the problem is, e.g. I'm always frustrated when [...]._
I notice every time i log onto a different toon, the location of the window is off. I have to relocate the location of the anchor each time i log on to a different toon. 

### What solution would you like?
_A clear and concise description of what you want to happen._

Allow to save the anchor location to each specific toon settings. 

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._
None

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._
None

**Comment by lucasvienna** [comment]
@Milky063 this functionality is outside of scope for a plugin, it would be best to ask directly in the BetterBags repo: https://github.com/Cidan/BetterBags
