### ISSUE TITLE
[BUG] Invalid items

### ISSUE THREAD

**Issue by zeptognome** [AvyAddons/BetterBags_Dragonflight#4]
### Description

The following items are unobtainable and have incomplete data making them unusable with BetterBags and can/should be removed from your categories

Primordial stones: 204026,204028,204008,204016,204024,204017
Drakewatcher Manuscripts: 197373,196990,197600,197119

Thanks

### Addon Version

v1.0.6

### World of Warcraft Flavor

Retail (Dragonflight)

### Tested with only BetterBags_Dragonflight

- [X] Yes
- [ ] No

### Reproduction Steps

With the current version of BetterBags, these items break the category window

### Screenshots

![image](https://github.com/AvyAddons/BetterBags_Dragonflight/assets/158738380/4323d61e-8f13-40a1-9010-d037248e289a)

**Comment by lucasvienna** [comment]
Thanks for the report, I've managed to resolve the issue for both the Manuscripts and Stones. I've also found a similar problem with the Treasure Sacks category and a few others for the Crafting sister addon.
